title: "Stat 850 Project"
author: "Firstname Lastname, Firstname Lastname, ..."
bibliography: references.bib

project:
  output-dir: _output
  render:
    - README.md
    - guidelines.qmd
    - proposal.qmd
    - report.qmd
    - slides.qmd
    - checklist.qmd

execute:
  echo: false
  message: false
  warning: false

toc: true
number-sections: true
