title: "Stat 850 Project"
author: "Firstname Lastname, Firstname Lastname, ..."
bibliography: references.bib

project:
  output-dir: _output
  render:
    - guidelines.qmd
    - proposal.qmd
    - report.qmd
    - slides.qmd
    - README.md

toc: true
number-sections: true
